//Activity1: Basic Eventhandling
const button = document.querySelector(".btn");
const paragraph = document.querySelector(".para");
button.addEventListener("click", () => {
  paragraph.textContent = "Hello, I'm new Paragraph";
});

const image = document.querySelector(".img");
image.addEventListener("dblclick", () => {
  if ((image.style.display = "none")) image.style.display = "block";
});

//Activity2: Mouse Events
const h4 = document.querySelector(".h4");
h4.addEventListener("mouseover", () => {
  h4.style.backgroundColor = "red";
});
h4.addEventListener("mouseout", () => {
  h4.style.backgroundColor = "yellow";
});

//Activity3: Keyboard Event

const input = document.querySelector(".input");
input.addEventListener("keydown", (e) => {
  console.log(e.key);
});
input.addEventListener("keyup", (e) => {
  paragraph.textContent = "hello I'm a new para generated by keyup event";
  document.body.appendChild(paragraph);
});

//Activity4: Form Events

const form = document.querySelector(".form");
form.addEventListener("submit", (e) => {
  e.preventDefault();
  const formData = new FormData(form);
  const name = formData.get("name");
  console.log(`my name is ${name}`);
});

const select = document.querySelector(".select");
const emptyPara = document.querySelector(".select-para");
select.addEventListener("change", (e) => {
  emptyPara.textContent = `value is ${e.target.value}`;
});

//Activity5: Event Delegation

const ul = document.querySelector(".ul");
ul.addEventListener("click", (e) => {
  if (e.target.nodeName == "LI") console.log(e.target.innerText);
});

const parentUi = document.querySelector(".parent-ul");
const buttonLi = document.querySelector(".btn-addLi");
let item = 3;

parentUi.addEventListener("click", (e) => {
  if (e.target && e.target.nodeName === "LI") {
    console.log(e.target.innerText);
  }
});

buttonLi.addEventListener("click", () => {
  item++;
  const li = document.createElement("li");
  li.innerText = `Item ${item}`;
  li.className = "li-4";
  parentUi.appendChild(li);
});
